package com.anterka.bjyotish.constants;

public enum NotificationTypeEnum {
    CONSULTATION_REMINDER,
    CONSULTATION_CONFIRMED,
    CONSULTATION_CANCELLED,
    SUBSCRIPTION_EXPIRY,
    DAILY_HOROSCOPE,
    TRANSIT_ALERT,
    SYSTEM_NOTIFICATION
}
